version: '3.8'

services:
  ms-gestion-cursos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-gestion-cursos
    env_file: .env
    environment:
      NODE_ENV: production
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4200
    ports:
      - "3001:3001"
    restart: unless-stopped
    command: sh -c "sleep 10 && node dist/index.js"
